name: tailwind_components
description: Flutter components based on Tailwind CSS.
version: 1.0.1
homepage: https://github.com/RobinVDVelden/tailwind_components.git

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  heroicons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
